### ISSUE TITLE
Failure at Error: Error 401 creating VeracodeFlaw label "VeracodeFlaw: Very High": Bad credentials

### ISSUE THREAD

**Issue by omegazeng** [buzzcode/veracode-flaws-to-issues#34]
``` yaml
    - name: import flaws as issues
      uses: buzzcode/veracode-flaws-to-issues@v1
      with:
        scan-results-json: 'filtered_results.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
```
```
Run buzzcode/veracode-flaws-to-issues@v1
Processing file: filtered_results.json
Importing pipeline flaws into  xxx/yyy.  2 seconds between imports (to handle GitHub rate limiting)
Creating VeracodeFlaw labels
Failure at Error: Error 401 creating VeracodeFlaw label "VeracodeFlaw: Very High": Bad credentials
    at /home/works/actions-runner/_work/_actions/buzzcode/veracode-flaws-to-issues/v1/label.js:95:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.createLabels (/home/works/actions-runner/_work/_actions/buzzcode/veracode-flaws-to-issues/v1/label.js:75:9)
    at async importFlaws (/home/works/actions-runner/_work/_actions/buzzcode/veracode-flaws-to-issues/v1/importer.js:5[6](https://git.example.com/xxx/yyy/runs/9223?check_suite_focus=true#step:4:6):5)
```
